---
- name: Crear usuarios
  hosts: all
  #vars:
    #password: Password1!
    
  tasks:
    - name: Creando el usuario "{{ uusername }}" 
      user:
        name: {{ uusername }}
        password: {{ upassword | password_hash('sha512') }}
      
    
