---
- name: Crear usuario
  hosts: all
  gather_facts: no
    
  tasks:
    - name: Creando el usuario "{{ uusername }}" 
      user:
        name: "{{ uusername }}"
        password: "{{ upassword | password_hash('sha512') }}"
        comment: "Creado con Ansible"
      register: usario
      
    - name: setear Cambio de Password en primer login
      shell: chage -d 0 {{ uusername }}
      when: usario.changed
