---
- name: Crear usuarios
  hosts: all
  gather_facts: no
  vars:
    upassword: Password1!
    
  tasks:
    - name: Creando el usuarios 
      user:
        name: "{{ item }}"
        password: "{{ upassword | password_hash('sha512') }}"
        comment: "Creado con Ansible"
      with_items: "{{ username }}"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution_file_variety == 'RedHat'      
      register: usario
            
      
      
#      update_password: on_create
      
#    - name: Forzar cambio de Password
#      shell: chage -d 0 {{ uusername }}
#      when: usario.changed



