---
- name: Remover usuarios
  hosts: all
    
  tasks:
    - name: Remover el usuarios 
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      with_items: "{{ username }}"

...